name: splitseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cycler=0.10.0
  - cython=0.29.14
  - dbus=1.13.6
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - htslib=1.10.2
  - icu=64.2
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.65.3
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.9.1
  - libxml2=2.9.10
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - ncurses=6.1
  - nspr=4.24
  - nss=3.47
  - numpy=1.17.5
  - openssl=1.1.1d
  - pandas=0.25.3
  - pcre=8.43
  - pip=20.0.1
  - pthread-stubs=0.4
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - python=3.6.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - qt=5.12.5
  - readline=8.0
  - samtools=1.10
  - scipy=1.4.1
  - setuptools=45.1.0
  - six=1.14.0
  - sqlite=3.30.1
  - star=2.7.3a
  - tk=8.6.10
  - tornado=6.0.3
  - wheel=0.33.6
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pysam==0.15.4
